#!/usr/bin/env bash
#a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)

# Install nginx
sudo apt update
sudo apt install -y nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
