#!/usr/bin/env bash
#Configuring my Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.linkedin.com/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >  | sudo tee -a /usr/share/nginx/html/page_error_404.html
sudo service nginx restart
