#!/usr/bin/env bash
#Configuring my Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a   rewrite ^/redirect_me https://www.linkedin.com/ permanent;' /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html >/dev/null

#Creating a default nginx default backkupr if things go wrong
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
sudo sed -i '$i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-enabled/default

sudo sed -i '$i add_header X-Served-By: 03-web-02;\n' /etc/nginx/sites-available/default
sudo service nginx restart
#Ensure you use sudo to create the custom 404 page.
