#!/usr/bin/env bash

# Check if the script is provided with the correct number of arguments
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 OLD_IP_ADDRESS NEW_IP_ADDRESS"
    exit 1
fi

# Accessing arguments
OLD_IP_ADDRESS=$1
NEW_IP_ADDRESS=$2

# Define the list of files to update
FILES=(
    "connect-web-02"
    "transfer-web-02"
    "not_found_2"
    "hello_world2"
    "redirect-check-02"
    "custom_404_page_02"
    "../0x10-https_ssl/connect-web-02"
 )

# Loop through each file and replace IP addresses
for file in "${FILES[@]}"; do
    # Check if the file exists
    if [ -f "$file" ]; then
        # Replace IP addresses with the new one
        sed -i "s/$OLD_IP_ADDRESS/$NEW_IP_ADDRESS/g" "$file"
    else
        echo "File not found: $file"
    fi
done

echo "IP addresses replaced: $OLD_IP_ADDRESS -> $NEW_IP_ADDRESS in the specified files."
