#!/usr/bin/env bash
#We stopped our 4-to_infinity_and_beyond process using ctrl+c in the previous task, there is actually another way to do this.
#Write a Bash script that stops 4-to_infinity_and_beyond process.
#You cannot use kill or killallkill
pkill "$(pgrep -f 4-to_infinity_and_beyond)"
