#!/usr/bin/env bash
#We stopped our  process using ctrl+c in the previous task, there is actually another way to do this.
#Write a Bash script that kills the process 7-highlander.
kill -9 "$(pgrep -f 7-highlander)"
