#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
"""
display hours from 0 to 12
display minutes from 1 to 59
"""
h=0
m=1
while [ $h -le 24 ];
do
    echo "Hour: $h"
    while [ $m -le 59 ];
    do
	echo "$m"
	((m++))
    done
    ((h++))
    m=0
done
